### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by mdm01** [pschmitt/zabbix-docker-armhf#1]
Hello pschmitt,
May I please ask you to share a sample docker compose file for pschmitt/zabbix-server-mysql-alpine-armhf?
I have been struggling to get it running on a rpi2, and without success so far! :(

Thanks a lot in advance.

**Comment by pschmitt** [comment]
You should get away just fine by using one from https://github.com/zabbix/zabbix-docker/ and switching the docker images names.

**Comment by pschmitt** [comment]
Fixed by 705605861950314297094d318fdcf958d1b7e922.
See current [README.md](https://github.com/pschmitt/zabbix-docker-multiarch/blob/master/README.md) for documentation
