### ISSUE TITLE
Any plans for supporting 5.x?

### ISSUE THREAD

**Issue by imkebe** [pschmitt/zabbix-docker-armhf#7]

**Comment by pschmitt** [comment]
Well, yeah 🤷‍♂

**Comment by pschmitt** [comment]
Have you checked out the 5.0 tags? The only thing that is broken seems to be the appliance images.

**Comment by imkebe** [comment]
I've chcecked an appliance one - that's why i havn't seen it. Btw why it's broken? Any help is needded?

**Comment by pschmitt** [comment]
2 things:

- I never managed to build the RHEL appliance properly. Let me know if you find any way to make it work. To test: `./build.sh zabbix-appliance-rhel`
- The other appliances are no longer provided upstream [as you can see here](https://github.com/zabbix/zabbix-docker/tree/7f50d6cb91123efd7d8d92fa25b4211e535a6ebf/zabbix-appliance)
